<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple Computer//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>log</string>
	</array>
	<key>name</key>
	<string>Log4j</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>comment</key>
			<string>Timestamp</string>
			<key>match</key>
			<!--2014-8-13 17:15:49 or 2014-8-13 17:15:49,345 or Sep 22, 2014 7:12:30 PM -->
			<string>(\d{4}-\d{1,2}-\d{1,2} \d{1,2}:\d{1,2}:\d{1,2}(,\d+)?)|(\w{3} \d{2}, \d{4} \d{1,2}:\d{1,2}:\d{1,2}( AM| PM)?)</string>
			<key>name</key>
			<string>entity.category.log4j</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>TRACE message</string>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>entity.trace.log4j</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>entity.trace.log4j</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>entity.trace.message.log4j</string>
				</dict>
				<key>4</key>
				<dict>
					<key>name</key>
					<string>entity.trace.message.log4j</string>
				</dict>
			</dict>
			<key>match</key>
			<string>(log4j:)?(TRACE):?\s+(\D+)\d*(.*)</string>
			<key>name</key>
			<string>string.quoted.log4j</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>INFO message</string>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>entity.info.log4j</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>entity.info.log4j</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>entity.info.message.log4j</string>
				</dict>
				<key>4</key>
				<dict>
					<key>name</key>
					<string>entity.info.message.log4j</string>
				</dict>
			</dict>
			<key>match</key>
			<string>(log4j:)?(INFO|信息|SEVERE):?\s+(\D+)\d*(.*)</string>
			<key>name</key>
			<string>string.quoted.log4j</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>DEBUG message</string>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>entity.debug.log4j</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>entity.debug.log4j</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>entity.debug.message.log4j</string>
				</dict>
				<key>4</key>
				<dict>
					<key>name</key>
					<string>entity.debug.message.log4j</string>
				</dict>
			</dict>
			<key>match</key>
			<string>(log4j:)?(DEBUG):?\s+(\D+)\d*(.*)</string>
			<key>name</key>
			<string>string.quoted.log4j</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>WARN message</string>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>entity.warn.log4j</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>entity.warn.log4j</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>entity.warn.message.log4j</string>
				</dict>
				<key>4</key>
				<dict>
					<key>name</key>
					<string>entity.warn.message.log4j</string>
				</dict>
			</dict>
			<key>match</key>
			<string>(log4j:)?(WARN|警告):?\s+(\D+)\d*(.*)</string>
			<key>name</key>
			<string>string.quoted.log4j</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>ERROR message</string>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>entity.error.log4j</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>entity.error.log4j</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>entity.error.message.log4j</string>
				</dict>
				<key>4</key>
				<dict>
					<key>name</key>
					<string>entity.error.message.log4j</string>
				</dict>
			</dict>
			<key>match</key>
			<string>(log4j:)?(ERROR|错误):?\s+(\D+)\d*(.*)</string>
			<key>name</key>
			<string>string.quoted.log4j</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>FATAL message</string>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>entity.fatal.log4j</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>entity.fatal.log4j</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>entity.fatal.message.log4j</string>
				</dict>
				<key>4</key>
				<dict>
					<key>name</key>
					<string>entity.fatal.message.log4j</string>
				</dict>
			</dict>
			<key>match</key>
			<string>(log4j:)?(FATAL|严重):?\s+(\D+)\d*(.*)</string>
			<key>name</key>
			<string>string.quoted.log4j</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>number</string>
			<key>match</key>
			<string>\d+</string>
			<key>name</key>
			<string>entity.number.log4j</string>
		</dict>
	</array>
	<key>scopeName</key>
	<string>source.log</string>
	<key>uuid</key>
	<string>56298a90-0c7f-45ce-9c9d-2ce24175893d</string>
</dict>
</plist>
